tasks:
  - init:
      bundle install --jobs 4 --retry 3
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - wingrunr21.vscode-ruby@0.26.0:VakXVw0C77hAQ3U3AZTn1Q==
#    - rebornix.ruby@0.26.0:RN+gv0dPjYfMqlcEEralhg==
    - Orta.vscode-danger@1.0.1:cGUzsroSPSoihE2Yps+qbA==
