name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
    - name: Code Checkout
      uses: actions/checkout@v1
    - name: Set Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Build Gem
      run: |
        gem build *.gemspec
    - name: Test Gem
      run: |
        rake test
